### ISSUE TITLE
ChannelOutboundHandlerAdapter() 接收的消息乱码，如何解决 ？

### ISSUE THREAD

**Issue by zhoutaoist** [hudaming1/jladder#13]
代码如下。尝试检查 content.content() 编码为 ISO8859-1，转码也不行，试过 GZIP 解压，非压缩格式
`ch.pipeline().addLast("reponseHandle", new ChannelOutboundHandlerAdapter() {`
`	@Override`
`   	public void write(ChannelHandlerContext ctx, Object msg, ChannelPromise promise) throws Exception {`
`			super.write(ctx, msg, promise);`
`			if (msg instanceof HttpContent) {`					
`					HttpContent content = (HttpContent)msg;`
`					if (msg.toString().contains("DefaultHttpContent")) {`
`							System.out.println("Content");`
`							ByteBuf buf = content.content();`
`							byte[] bytes = new byte[buf.readableBytes()];`
`							buf.readBytes(bytes);`
`							buf.resetReaderIndex();`						
`							System.out.println("\t" + new String(bytes));`
`					}`
`			}`

**Comment by hudaming1** [comment]
不好意思，代码已经重构，没有找到这段代码了
