### ISSUE TITLE
Chrome开启代理发送https请求时，无法处理3xx重定向

### ISSUE THREAD

**Issue by hudaming1** [hudaming1/jladder#8]
在Chrome做代理做鉴权时，服务端判断客户端身份不合法时期望直接发送3xx重定向响应，跳转到登录页，Firefox在代理接收Http和Https响应时，处理比较宽松，服务端直接返回3xx即可跳转。但Chrome在代理时对Http的响应报文格式要求十分严格（期初我3xx报文多了一个空格，始终就跳不过去），而且在等待Https响应时，貌似只接受1种选择，即"Http1.1 200 Connection establishing"，然后随即进入ssl握手阶段；因此服务端在返回非"http1.1 200 Connection..."响应时，Chrome直接拒绝处理，关闭连接。

因此，后续在针对Chrome的Https解决方案时，需要服务端支持SSL套件，跟Chrome模拟出ssl通信，也一样可以做到3xx重定向。

**Comment by qianqian512** [comment]
关于Chrome对代理详情处理严格参考：
https://groups.google.com/forum/#!msg/jasig-cas-user/TWaFzCEVTyk/V0bcMxxdfpsJ
    Chrome对于返回的响应头过于严格？（the HTTP  protocol requires an empty line tailing the headers and the filter  apparently does not send one.）

**Comment by qianqian512** [comment]
发现Firefox也无法重定向https了。。。。

**Comment by hudaming1** [comment]
鉴权功能close掉了
